<?xml version="1.0" encoding="utf-8"?><Database Name="RequestLogging" Class="LogEmDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ASPIRE\SQLEXPRESSTOM;Initial Catalog=RequestLogging;Persist Security Info=True;User ID=LogEmUser" SettingsObjectName="LogEm.Properties.Settings" SettingsPropertyName="RequestLoggingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="logEm.ResourceRequest" Member="ResourceRequests">
    <Type Name="ResourceRequest">
      <Column Name="ResourceRequestID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Application" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Host" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[User]" Member="User" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Sequence" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fkSessionID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Session_ResourceRequest" Member="Session" ThisKey="fkSessionID" OtherKey="SessionID" Type="Session" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="logEm.Session" Member="Sessions">
    <Type Name="Session">
      <Column Name="SessionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Application" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Host" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[User]" Member="User" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Sequence" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ASPSessionID" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="SessionBeginTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SessionEndTimeUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Session_ResourceRequest" Member="ResourceRequests" ThisKey="SessionID" OtherKey="fkSessionID" Type="ResourceRequest" />
    </Type>
  </Table>
</Database>